export default {
  JUMP_TO: 'navigator/JUMP_TO',
  JUMP_TO_INDEX: 'navigator/JUMP_TO_INDEX',
  PUSH_ROUTE: 'navigator/PUSH_ROUTE',
  POP_ROUTE: 'navigator/POP_ROUTE',
  POP_TO: 'navigator/POP_TO',
  POP_TO_INDEX: 'navigator/POP_TO_INDEX',
  POP_N: 'navigator/POP_N',
  RESET_ROUTE: 'navigator/RESET_ROUTE',
  REPLACE: 'navigator/REPLACE',
  REPLACE_AT: 'navigator/REPLACE_AT',
  REPLACE_AT_INDEX: 'navigator/REPLACE_AT_INDEX',
  BACK: 'navigator/BACK',
  FORWARD: 'navigator/FORWARD',
};
